In [1]:
%load_ext nb_black

<IPython.core.display.Javascript object>

In [28]:
import numpy as np
import tensorflow as tf


from tensorflow.keras.layers import (
    Dense,
    Conv1D,
    Conv2D,
    GlobalAveragePooling1D,
    MaxPooling1D,
    MaxPooling2D,
)
from tensorflow.keras.models import Sequential


from tensorflow.keras.utils import set_random_seed


<IPython.core.display.Javascript object>

# Testing Convolution Layer

In [3]:
m = np.array([[[1, 1, 1], [10, 10, 10], [20, 20, 20], [20, 20, 20]]], dtype="float")


def conv_layer(m, filters: int, kernel_size: int, strides: int) -> Conv1D:
    set_random_seed(42)

    c = Conv1D(
        filters=filters,
        kernel_size=kernel_size,
        strides=strides,
        name="conv_1d",
        use_bias=False,
    )

    print(m.shape)
    print(c.__call__(m))
    return c

<IPython.core.display.Javascript object>

## filters: 1
## kernel_size: 1
## strides: 1

In [4]:
c = conv_layer(m, filters=1, kernel_size=1, strides=1)

(1, 4, 3)
tf.Tensor(
[[[ 0.92965084]
  [ 9.296509  ]
  [18.593018  ]
  [18.593018  ]]], shape=(1, 4, 1), dtype=float32)


<IPython.core.display.Javascript object>

In [5]:
# column i corresponds to filter i

weights = c.weights[0].numpy()
print(weights.shape)
weights

(1, 3, 1)


array([[[ 0.8773805 ],
        [ 0.3983569 ],
        [-0.34608656]]], dtype=float32)

<IPython.core.display.Javascript object>

In [6]:
for i in range(0, m.shape[1]):
    a = np.dot(m[0][i], weights[0])
    print(a)

[0.92965084]
[9.29650843]
[18.59301686]
[18.59301686]


<IPython.core.display.Javascript object>

## filters: 2
## kernel_size: 1
## strides: 1

In [7]:
c = conv_layer(m, filters=2, kernel_size=1, strides=1)

(1, 4, 3)
tf.Tensor(
[[[-0.44921798  1.6759224 ]
  [-4.4921794  16.759224  ]
  [-8.984359   33.518448  ]
  [-8.984359   33.518448  ]]], shape=(1, 4, 2), dtype=float32)


<IPython.core.display.Javascript object>

In [8]:
# column i corresponds to filter i
weights = c.weights[0].numpy()
print(weights.shape)
weights

(1, 3, 2)


array([[[ 0.7847531 ,  0.3563013 ],
        [-0.3095492 ,  0.98587775],
        [-0.92442185,  0.33374333]]], dtype=float32)

<IPython.core.display.Javascript object>

In [9]:
first_filter = weights[:, :, 0].reshape(-1, 1)
second_filter = weights[:, :, 1].reshape(-1, 1)

# first filter
print(f"first_filter\n")
for i in range(4):
    print(np.dot(m[0][i], first_filter))


# second filter
print(f"\nsecond_filter\n")
for i in range(4):
    print(np.dot(m[0][i], second_filter))


first_filter

[-0.44921798]
[-4.49217975]
[-8.9843595]
[-8.9843595]

second_filter

[1.67592239]
[16.75922394]
[33.51844788]
[33.51844788]


<IPython.core.display.Javascript object>

# filters: 1
# kernel_size: 2
# strides: 1

In [10]:
c = conv_layer(m, filters=1, kernel_size=2, strides=1)

(1, 4, 3)
tf.Tensor(
[[[ 3.7816882]
  [12.822274 ]
  [19.3959   ]]], shape=(1, 3, 1), dtype=float32)


<IPython.core.display.Javascript object>

In [11]:
weights = c.weights[0].numpy()
print(weights.shape)
weights

(2, 3, 1)


array([[[ 0.6204017 ],
        [ 0.28168088],
        [-0.2447201 ]],

       [[ 0.7794048 ],
        [-0.7308196 ],
        [ 0.2638473 ]]], dtype=float32)

<IPython.core.display.Javascript object>

In [12]:
for i in range(0, 4):
    try:
        print(np.dot(m[0][i], weights[0]) + np.dot(m[0][i + 1], weights[1]))
    except:
        pass

[3.78168774]
[12.82227516]
[19.39589977]


<IPython.core.display.Javascript object>

# filters: 1
# kernel_size: 3
# strides: 1

In [13]:
c = conv_layer(m, filters=1, kernel_size=3, strides=1)

(1, 4, 3)
tf.Tensor(
[[[ 7.675482]
  [15.057091]]], shape=(1, 2, 1), dtype=float32)


<IPython.core.display.Javascript object>

In [14]:
weights = c.weights[0].numpy()
print(weights.shape)
weights

(3, 3, 1)


array([[[ 0.50655586],
        [ 0.2299915 ],
        [-0.19981313]],

       [[ 0.6363813 ],
        [-0.5967117 ],
        [ 0.21543044]],

       [[ 0.66538733],
        [-0.46964318],
        [ 0.03364313]]], dtype=float32)

<IPython.core.display.Javascript object>

In [15]:
print(m)

[[[ 1.  1.  1.]
  [10. 10. 10.]
  [20. 20. 20.]
  [20. 20. 20.]]]


<IPython.core.display.Javascript object>

In [16]:
for i in range(0, 4):
    try:
        print(
            np.dot(m[0][i], weights[0])
            + np.dot(m[0][i + 1], weights[1])
            + np.dot(m[0][i + 2], weights[2])
        )
    except:
        pass

[7.6754806]
[15.05708933]


<IPython.core.display.Javascript object>

# filters: 1
# kernel_size: 1
# strides: 2

In [17]:
c = conv_layer(m, filters=1, kernel_size=1, strides=2)

(1, 4, 3)
tf.Tensor(
[[[ 0.92965084]
  [18.593018  ]]], shape=(1, 2, 1), dtype=float32)


<IPython.core.display.Javascript object>

In [18]:
weights = c.weights[0].numpy()
print(weights.shape)
weights

(1, 3, 1)


array([[[ 0.8773805 ],
        [ 0.3983569 ],
        [-0.34608656]]], dtype=float32)

<IPython.core.display.Javascript object>

<div class="alert alert-info">
    
    
It's like the example with `filters:1`, `kernel_size:1`, `strides:1`, but we skip the second and the fourth element
    
</div>

# filters: 3
# kernel_size: 2
# strides: 1

In [19]:
c = conv_layer(m, filters=3, kernel_size=2, strides=1)

(1, 4, 3)
tf.Tensor(
[[[ 14.005341  -13.909505   -5.0180826]
  [ 42.47728   -34.50992    -9.642081 ]
  [ 60.560524  -42.87355    -9.149477 ]]], shape=(1, 3, 3), dtype=float32)


<IPython.core.display.Javascript object>

In [20]:
# column i  corresponds to filter i

weights = c.weights[0].numpy()
print(weights.shape)
weights

(2, 3, 3)


array([[[ 0.50655586,  0.2299915 , -0.19981313],
        [ 0.6363813 , -0.5967117 ,  0.21543044],
        [ 0.66538733, -0.46964318,  0.03364313]],

       [[ 0.18492198, -0.58489287, -0.07586199],
        [ 0.65907115, -0.04194403,  0.00416678],
        [ 0.37570852, -0.6804772 , -0.4350391 ]]], dtype=float32)

<IPython.core.display.Javascript object>

In [21]:
print(m)

[[[ 1.  1.  1.]
  [10. 10. 10.]
  [20. 20. 20.]
  [20. 20. 20.]]]


<IPython.core.display.Javascript object>

In [22]:
for i in range(0, 4):
    try:
        print(np.dot(m[0][i], weights[0][:, 0]) + np.dot(m[0][i + 1], weights[1][:, 0]))
    except:
        pass

14.005340993404388
42.47727811336517
60.56052327156067


<IPython.core.display.Javascript object>

<div class='alert alert-info'>
    
    
- Shape of filter: (`kernel_size`, `feature_shape (n_cols)`, `n_filters`)
- Shape of `Conv1D` output: (`1`, `steps`, `n_filters`), where `steps` is defined below.


    
</div>

In [23]:
def get_steps(feature_shape: int, kernel_size: int, strides: int) -> int:
    steps = 0

    if feature_shape < kernel_size:
        raise ValueError(
            f"kernel size {kernel_size} should be <= feature shape {feature_shape}"
        )

    for i in range(0, feature_shape, strides):
        if i + kernel_size <= feature_shape:
            steps += 1
    return steps

<IPython.core.display.Javascript object>

In [24]:
steps = get_steps(feature_shape=10, kernel_size=5, strides=2)
steps

3

<IPython.core.display.Javascript object>

## Global Average Pooling

In [25]:
a = np.array([[[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400]]], dtype="float32")
a

array([[[  1.,   2.,   3.,   4.],
        [ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.]]], dtype=float32)

<IPython.core.display.Javascript object>

In [29]:
GlobalAveragePooling1D(data_format="channels_last", keepdims=False)(a)

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[ 37.,  74., 111., 148.]], dtype=float32)>

<IPython.core.display.Javascript object>

In [30]:
GlobalAveragePooling1D(data_format="channels_first", keepdims=False)(a)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[  2.5,  25. , 250. ]], dtype=float32)>

<IPython.core.display.Javascript object>

# Global Max Pooling

In [31]:
MaxPooling1D(pool_size=1, strides=1, padding="same", name="max_pooling_1")(a)

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[  1.,   2.,   3.,   4.],
        [ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.]]], dtype=float32)>

<IPython.core.display.Javascript object>

In [32]:
MaxPooling1D(pool_size=2, strides=1, padding="same", name="max_pooling_1")(a)

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.],
        [100., 200., 300., 400.]]], dtype=float32)>

<IPython.core.display.Javascript object>

In [33]:
# Padding evenly up and down
MaxPooling1D(pool_size=3, strides=1, padding="same", name="max_pooling_1")(a)


# [
#   [0, 0, 0, 0],
#   [1, 2, 3, 4]
#   [10, 20, 30, 40]
#   [100, 200, 300, 400]
#   [0, 0, 0, 0]
# ]

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.],
        [100., 200., 300., 400.]]], dtype=float32)>

<IPython.core.display.Javascript object>