In [1]:
%load_ext nb_black

<IPython.core.display.Javascript object>

In [2]:
import numpy as np

from tensorflow.keras.layers import (
    GlobalAveragePooling1D,
    GlobalMaxPooling1D,
    MaxPooling1D,
)

<IPython.core.display.Javascript object>

In [3]:
a = np.array([[[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400]]], dtype="float32")
a

array([[[  1.,   2.,   3.,   4.],
        [ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.]]], dtype=float32)

<IPython.core.display.Javascript object>

# GlobalAveragePooling

In [4]:
GlobalAveragePooling1D(data_format="channels_last", keepdims=False)(a)

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[ 37.,  74., 111., 148.]], dtype=float32)>

<IPython.core.display.Javascript object>

In [5]:
GlobalAveragePooling1D(data_format="channels_first", keepdims=False)(a)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[  2.5,  25. , 250. ]], dtype=float32)>

<IPython.core.display.Javascript object>

# Max pooling

In [6]:
a

array([[[  1.,   2.,   3.,   4.],
        [ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.]]], dtype=float32)

<IPython.core.display.Javascript object>

In [7]:
MaxPooling1D(pool_size=1, strides=1, padding="same", name="max_pooling_1")(a)

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[  1.,   2.,   3.,   4.],
        [ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.]]], dtype=float32)>

<IPython.core.display.Javascript object>

In [8]:
a

array([[[  1.,   2.,   3.,   4.],
        [ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.]]], dtype=float32)

<IPython.core.display.Javascript object>

In [9]:
MaxPooling1D(pool_size=2, strides=1, padding="same", name="max_pooling_1")(a)

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.],
        [100., 200., 300., 400.]]], dtype=float32)>

<IPython.core.display.Javascript object>

In [10]:
MaxPooling1D(pool_size=2, strides=1, padding="valid", name="max_pooling_1")(a)

<tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
array([[[ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.]]], dtype=float32)>

<IPython.core.display.Javascript object>

In [11]:
a

array([[[  1.,   2.,   3.,   4.],
        [ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.]]], dtype=float32)

<IPython.core.display.Javascript object>

In [12]:
# Padding evenly up and down
MaxPooling1D(pool_size=3, strides=1, padding="same", name="max_pooling_1")(a)

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[ 10.,  20.,  30.,  40.],
        [100., 200., 300., 400.],
        [100., 200., 300., 400.]]], dtype=float32)>

<IPython.core.display.Javascript object>